language: python
python: '2.7'
sudo: false
addons:
  apt:
    packages:
    - python-pip
install:
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- ansible-playbook tests/test.yml -i tests/inventory --syntax-check
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
deploy:
  api_key:
    secure: gl7p6jKUKXcTOA77DQ82HSZa0WupBvAaM51UYcrujCBCnHIvx+scse7buf0iCt0K9/h7m2tnei+rvNqy+rxuBckGOWJ64WNFGalI2ryl/uTsDZN8YoL6oY/Aa5AfREkWP/aUIstVPiExyFwxYuGBRrCElLZdNYQTQ1kp8KNMiPEW+X4co8beEWrnXyueoqsjSMFU2vmyqdzdp9rK1VAahZniqQSmKORaR9cOlVseeNv9zFt6CcBjYmOhuZJB2tv/1bhgmM6An2EjXKHbqx2Y9zRToAAHj7xEekMgDWf/zI0h+Kr1kv7B83oeqqYJaFjqAGFOmWNK9kcLc8nEgfyJo6gjHDFOGxRd6csYc8cixlZ0hdnD3Q0VcNlib+7uBZH2SFmLqP9VOUEORu0z7W+QR6NlrowaaK8jaAQX29zVczclyaSYae2sWKfvQwRUBKMQSn2NgJFuadoRJXbrJMAnQTtlkU23+Am2qyosy4ZZO5mvESF0slAJC5r3/sj3Y5qfGvaaSlS3lixPsIDaQiU4FBdo14m0l88H82b4RjJmEqUDEnHAS1OnNeluhVrxRxIiw1wz78Ficih1w1c/YEBRppLgo2AgLxV2UF3rM6IWZ+XpydFfigb0GNbqQb8uZkDvP91UScLIDxAgCaWd3O4rDTGdVDHxKQFd8zNwbMcX89I=
