---
- debug:
    msg: "I want to Test the integration inside {{project_to_integrate}}"

- name: Download project from git
  git:
    repo: "{{project_to_integrate['repo_url']}}"
    version:  "{{project_to_integrate['branch']}}"
    dest: "{{project_integration_test_dir}}/{{project_to_integrate['project_name']}}"

- name: Replace module uri inside package.json
  json_file_replacer:
    path: "{{project_integration_test_dir}}/{{project_to_integrate['project_name']}}/package.json"
    keyToFind: "{{project['project_name']}}"
    valueToReplace: "git+{{project['repo_url']}}#{{project['branch']}}"
    backup: True

- name: Install libraries
  command: npm install --silent
  args:
    chdir: "{{project_integration_test_dir}}/{{project_to_integrate['project_name']}}"

- name: Build package module
  command: smild build
  args:
    chdir: "{{project_integration_test_dir}}/{{project_to_integrate['project_name']}}/node_modules/{{project['project_name']}}"

- name: smild-ansible
  include_role:
    name: tierratelematics.smild-ansible
  vars:
    project_name: "{{project_to_integrate['project_name']}}"
    project_root_dir: "{{project_integration_test_dir}}/{{project_to_integrate['project_name']}}"
    create_version_files: False